# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 737899b8c2c4df668c16cca33b7d3abb343f12f16710749d9f0372724f5f7fac073db5575ecad902fde4a2fd350e7bd3d0f4fc72eb2c6348348fe10e543d6bdd

test:
  secret_key_base: ad1f7420da5e7d64d9e98f559ddcbb743090fb15e28949e07734b1f2aaffffde8a71e36e022f187d0c3e9edee67c7c5c9f02d1aa7f4d75273ec0a4d58b29e25e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
